apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-ekstern-integrasjon
  namespace: teamdagpenger
  labels:
    team: teamdagpenger

spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/readyness
    initialDelay: 30
    failureThreshold: 10
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: {{ limitsMemory }}
    requests:
      memory: {{ requestsMemory }}
      cpu: {{ requestsCpu }}
  accessPolicy:
    outbound:
      external:
        - host: dp-iverksett.intern.dev.nav.no
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "vedtak.read"
          enabled: true
          product: "dagpenger"
          allowedIntegrations:
            - maskinporten
          atMaxAge: 120
          consumers:
            - name: NAV
              orgno: "889640782"
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        cascadingDelete: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: dp-ekstern-integrasjon
            envVarPrefix: DB
  ingresses:
  {{#each ingresses as |url|}}
     - {{ url }}
         {{/each}}
